# Generated by Django 2.2 on 2020-01-27 02:18

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('drink', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Sale',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.PositiveIntegerField(default=1, verbose_name='Количество')),
                ('drink', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='drink', to='drink.Drink', verbose_name='Напиток')),
            ],
        ),
    ]
